### ISSUE TITLE
Jobs list is not working

### ISSUE THREAD

**Issue by roher-roher** [bacularis/bacularis-app#11]
Hi, when I am trying to open a list of jobs by clicking on the "Jobs" item in the left panel (URL: /web/job/), I am getting the following error page:

> Error
> Description
> Class 'ResourceBundle' not found
> 
> Source File
> ${PradoFramework}/I18N/core/CultureInfo.php (219)
> 
> 0208:      * @param string $culture the culture identifier.
> 0209:      * @param mixed $key
> 0210:      */
> 0211:     protected function loadCultureData($key)
> 0212:     {
> 0213:         foreach (self::$bundleNames as $bundleKey => $bundleName) {
> 0214:             if ($key == $bundleKey) {
> 0215:                 if (!array_key_exists($this->culture, self::$data)) {
> 0216:                     self::$data[$this->culture] = [];
> 0217:                 }
> 0218: 
> 0219:                 self::$data[$this->culture][$bundleKey] = \ResourceBundle::create($this->culture, $bundleName, true);
> 0220:                 break;
> 0221:             }
> 0222:         }
> 0223:     }
> 0224: 
> 0225:     /**
> 0226:      * Find the specific ICU data information from the data.
> 0227:      * The path to the specific ICU data is separated with a slash "/".
> 0228:      * E.g. To find the default calendar used by the culture, the path
> 0229:      * "calendar/default" will return the corresponding default calendar.
> 0230:      * @param string $path the data you want to find.
> 0231:      * @param string $key bundle name.
> 
> Stack Trace
> #0 ${PradoFramework}/I18N/core/CultureInfo.php(248): Prado\I18N\core\CultureInfo->loadCultureData('Core')
> #1 ${PradoFramework}/Web/UI/WebControls/TDatePicker.php(579): Prado\I18N\core\CultureInfo->findInfo('calendar/gregor...')
> #2 ${PradoFramework}/Web/UI/WebControls/TDatePicker.php(558): Prado\Web\UI\WebControls\TDatePicker->getCulturalOptions()
> #3 ${PradoFramework}/Web/UI/WebControls/TDatePicker.php(908): Prado\Web\UI\WebControls\TDatePicker->getDatePickerOptions()
> #4 ${PradoFramework}/Web/UI/WebControls/TTextBox.php(217): Prado\Web\UI\WebControls\TDatePicker->renderClientControlScript(Object(Prado\Web\UI\THtmlWriter))
> #5 ${PradoFramework}/Web/UI/WebControls/TDatePicker.php(883): Prado\Web\UI\WebControls\TTextBox->addAttributesToRender(Object(Prado\Web\UI\THtmlWriter))
> #6 ${PradoFramework}/Web/UI/WebControls/TWebControl.php(488): Prado\Web\UI\WebControls\TDatePicker->addAttributesToRender(Object(Prado\Web\UI\THtmlWriter))
> #7 ${PradoFramework}/Web/UI/WebControls/TTextBox.php(362): Prado\Web\UI\WebControls\TWebControl->renderBeginTag(Object(Prado\Web\UI\THtmlWriter))
> #8 ${PradoFramework}/Web/UI/WebControls/TWebControl.php(471): Prado\Web\UI\WebControls\TTextBox->renderBeginTag(Object(Prado\Web\UI\THtmlWriter))
> #9 ${PradoFramework}/Web/UI/WebControls/TDatePicker.php(430): Prado\Web\UI\WebControls\TWebControl->render(Object(Prado\Web\UI\THtmlWriter))
> #10 ${PradoFramework}/Web/UI/TControl.php(1580): Prado\Web\UI\WebControls\TDatePicker->render(Object(Prado\Web\UI\THtmlWriter))
> #11 ${PradoFramework}/Web/UI/TControl.php(1610): Prado\Web\UI\TControl->renderControl(Object(Prado\Web\UI\THtmlWriter))
> #12 ${PradoFramework}/Web/UI/TControl.php(1594): Prado\Web\UI\TControl->renderChildren(Object(Prado\Web\UI\THtmlWriter))
> #13 ${PradoFramework}/Web/UI/TControl.php(1580): Prado\Web\UI\TControl->render(Object(Prado\Web\UI\THtmlWriter))
> #14 ${PradoFramework}/Web/UI/TControl.php(1610): Prado\Web\UI\TControl->renderControl(Object(Prado\Web\UI\THtmlWriter))
> #15 ${PradoFramework}/Web/UI/TForm.php(89): Prado\Web\UI\TControl->renderChildren(Object(Prado\Web\UI\THtmlWriter))
> #16 ${PradoFramework}/Web/UI/TControl.php(1580): Prado\Web\UI\TForm->render(Object(Prado\Web\UI\THtmlWriter))
> #17 ${PradoFramework}/Web/UI/TControl.php(1610): Prado\Web\UI\TControl->renderControl(Object(Prado\Web\UI\THtmlWriter))
> #18 ${PradoFramework}/Web/UI/TControl.php(1594): Prado\Web\UI\TControl->renderChildren(Object(Prado\Web\UI\THtmlWriter))
> #19 ${PradoFramework}/Web/UI/TControl.php(1580): Prado\Web\UI\TControl->render(Object(Prado\Web\UI\THtmlWriter))
> #20 ${PradoFramework}/Web/UI/TControl.php(1610): Prado\Web\UI\TControl->renderControl(Object(Prado\Web\UI\THtmlWriter))
> #21 ${PradoFramework}/Web/UI/TControl.php(1594): Prado\Web\UI\TControl->renderChildren(Object(Prado\Web\UI\THtmlWriter))
> #22 ${PradoFramework}/Web/UI/TControl.php(1580): Prado\Web\UI\TControl->render(Object(Prado\Web\UI\THtmlWriter))
> #23 ${PradoFramework}/Web/UI/TPage.php(244): Prado\Web\UI\TControl->renderControl(Object(Prado\Web\UI\THtmlWriter))
> #24 ${PradoFramework}/Web/UI/TPage.php(209): Prado\Web\UI\TPage->processNormalRequest(Object(Prado\Web\UI\THtmlWriter))
> #25 ${PradoFramework}/Web/Services/TPageService.php(527): Prado\Web\UI\TPage->run(Object(Prado\Web\UI\THtmlWriter))
> #26 ${PradoFramework}/Web/Services/TPageService.php(464): Prado\Web\Services\TPageService->runPage(Object(JobList), Array)
> #27 ${PradoFramework}/TApplication.php(1189): Prado\Web\Services\TPageService->run()
> #28 ${PradoFramework}/TApplication.php(381): Prado\TApplication->runService()
> #29 ${DocumentRoot}/index.php(43): Prado\TApplication->run()
> #30 {main}

I am using bacularis 1.6.0 on Debian 10 (installed from a deb package).

**Comment by ganiuszka** [comment]
Hello roher-roher,

Thank you for your report.

This error is about missing the Bacularis package dependency which is ``php-intl``. It is strange because the ``bacularis`` package has it defined in the dependency list. So, maybe from some reason this ``php-intl`` has been uninstalled from your system or disabled in PHP settings?

To solve it I would propose to install it by this command:

```
apt install php-intl
```

and after installing to apply changes you can restart PHP-FPM:

```
systemctl restart php7.3-fpm
```

Good luck. Please let us know if it helped.

Best regards,
Marcin Haba (gani)

**Comment by roher-roher** [comment]
Hi @ganiuszka ,

The php-intl package is already installed:

> $ apt show php-intl
> Package: php-intl
> Version: 2:7.3+69
> Priority: optional
> Section: php
> Source: php-defaults (69)
> Maintainer: Debian PHP Maintainers <team+pkg-php@tracker.debian.org>
> Installed-Size: 12,3 kB
> Depends: php-common, php7.3-intl
> Download-Size: 5 996 B
> APT-Manual-Installed: yes
> APT-Sources: http://ftp.ru.debian.org/debian buster/main amd64 Packages
> Description: Internationalisation module for PHP [default]
>  This package provides a Internationalisation module for PHP.
>  .
>  PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used
>  open source general-purpose scripting language that is especially suited
>  for web development and can be embedded into HTML.
>  .
>  This package is a dependency package, which depends on Debian's default
>  PHP version (currently 7.3).

I have restarted php7.3-fpm:

> $ systemctl restart php7.3-fpm
> $ systemctl status php7.3-fpm
> ● php7.3-fpm.service - The PHP 7.3 FastCGI Process Manager
>    Loaded: loaded (/lib/systemd/system/php7.3-fpm.service; enabled; vendor preset: enabled)
>    Active: active (running) since Thu 2023-07-13 12:25:20 MSK; 5s ago
>      Docs: man:php-fpm7.3(8)
>  Main PID: 7796 (php-fpm7.3)
>    Status: "Ready to handle connections"
>     Tasks: 3 (limit: 4682)
>    Memory: 11.2M
>    CGroup: /system.slice/php7.3-fpm.service
>            ├─7796 php-fpm: master process (/etc/php/7.3/fpm/php-fpm.conf)
>            ├─7798 php-fpm: pool www
>            └─7799 php-fpm: pool www
> 
> July 13 12:25:20 home systemd[1]: Starting The PHP 7.3 FastCGI Process Manager...
> July 13 12:25:20 home systemd[1]: Started The PHP 7.3 FastCGI Process Manager.

I have also restarted my Apache server, just in case, but the error still persists,

**Comment by ganiuszka** [comment]
Hello roher-roher,

Thanks for checking it.

Could you also check if ``php-intl`` is loaded for PHP-FPM?

```
php-fpm7.3 -m | grep intl
```

Thanks in advance.

Best regards,
Marcin Haba (gani)

**Comment by roher-roher** [comment]
Looks like it's loaded, here is the result:

> $ php-fpm7.3 -m | grep intl
> intl

**Comment by ganiuszka** [comment]
Hello roher-roher,

Thanks for this checking. It is interesting.

The last thing that comes to my head to check is to temporary write in the Bacularis ``/usr/share/bacularis/htdocs/index.php`` file the following two lines just after the first line with ``<?php``:

```
phpinfo();
exit();
```

So after this modification first three lines could look like this:

```
<?php
phpinfo();
exit();
```

At the end please go to the web browser and load the Bacularis page. You should see output page with all PHP settings. Could I ask you about checking the ``intl`` module there?

Thanks in advance for one more test.

Best regards,
Marcin Haba (gani)

**Comment by roher-roher** [comment]
Hmm, intl is not found there:
![image](https://github.com/bacularis/bacularis-app/assets/6007995/e90efd09-c71a-4f70-b746-dad7221d99b3)

**Comment by ganiuszka** [comment]
Hello roher-roher,

Thank you for providing the ``phpinfo()`` page.

So, you don't use PHP-FPM, but you use Apache PHP module to serve PHP.

To enable ``intl`` module in your environment you can execute from the root account:

```
echo 'extension=intl.so' > /etc/php/7.3/apache2/conf.d/20-intl.ini
```

After that please restart the web server:

```
systemctl restart apache2
```

Please let us know if it helped.

Thanks.

Best regards,
Marcin Haba (gani)

**Comment by roher-roher** [comment]
Hello! Thank you, that has helped - jobs list is working now!

**Comment by ganiuszka** [comment]
Hello roher-roher,

Great. Thanks for your feedback :-)

I am closing this ticket.

Best regards,
Marcin Haba (gani)
