### ISSUE TITLE
PDOException "Column not found: 1054 Unknown column 'File.Filename' in 'field list'" in BaculumAPIClient.php when trying to access Job files in Job details

### ISSUE THREAD

**Issue by nisori** [bacularis/bacularis-app#16]
Hi Marcin,

I'm afraid it's me again, and I bet this problem has a similar root cause (incorrect database structure) as [issue 7](https://github.com/bacularis/bacularis-app/issues/7) had.

The issue is that the job files table is always empty, but it is not caused by the reason described [here](https://bacularis.app/doc/brief/troubleshooting.html#the-job-history-list-or-the-job-files-table-is-empty).

Instead, the debug log says __"Column not found: 1054 Unknown column 'File.Filename' in 'field list'__":

```
2023-09-05 13:42:13 [Application] BaculumAPIClient.php:189: API REQUEST ==> https://localhost:9097/api/v2/jobs/6734/files/?offset=0&limit=100&type=saved+items&details=1&director=orion-dir

2023-09-05 13:42:13 [Application] BaculumAPIClient.php:459: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>PDOException</title>
<style type="text/css">
/*<![CDATA[*/
body {font-family:"Verdana";font-weight:normal;color:black;background-color:white;}
h1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
h2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
h3 {font-family:"Verdana";font-weight:bold;font-size:11pt}
p {font-family:"Verdana";font-weight:normal;color:black;font-size:9pt;margin-top: -5px}
a {font-family:"Verdana";color:red;}
code,pre {font-family:"Lucida Console";font-size:10pt;}
td,.version {color: gray;font-size:8pt;border-top:1px solid #aaaaaa;}
.source {font-family:"Lucida Console";font-weight:normal;background-color:#ffffee;}
.error {background-color: #ffeeee;}/*]]>*/
</style>
</head>
<body>
<h1>PDOException</h1>
<h3>Description</h3>
<p style="color:maroon">SQLSTATE[42S22]: Column not found: 1054 Unknown column 'File.Filename' in 'field list'</p>
<h3>Source File</h3>
<p>/usr/share/bacularis/protected/vendor/bacularis/bacularis-api/API/Modules/Database.php (252)</p>
<div class="source">
<code><pre>
0241:         $connection = JobRecord::finder()-&gt;getDbConnection();
0242:         $pdo = $connection-&gt;getPdoInstance();
0243:         if (count($params) &gt; 0) {
0244:             $statement = $pdo-&gt;prepare($sql);
0245:             foreach ($params as $param =&gt; $value) {
0246:                 $key = $param[0] === ':' ? $param : ':' . $param;
0247:                 $type = TDbCommandBuilder::getPdoType($value);
0248:                 $statement-&gt;bindValue($key, $value, $type);
0249:             }
0250:             $statement-&gt;execute();
0251:         } else {
<div class="error">0252:             $statement = $pdo-&gt;query($sql);
</div>0253:         }
0254:         return $statement-&gt;fetchAll($fetch_opts);
0255:     }
0256: }

</pre></code>
</div>
<h3>Stack Trace</h3>
<div class="source">
<code><pre>
#0 /usr/share/bacularis/protected/vendor/bacularis/bacularis-api/API/Modules/Database.php(252): PDO-&gt;query()
#1 /usr/share/bacularis/protected/vendor/bacularis/bacularis-api/API/Modules/JobManager.php(536): Bacularis\API\Modules\Database::findAllBySql()
#2 /usr/share/bacularis/protected/vendor/bacularis/bacularis-api/API/Pages/API/JobListFiles.php(133): Bacularis\API\Modules\JobManager-&gt;getJobFiles()
#3 /usr/share/bacularis/protected/vendor/bacularis/bacularis-api/API/Pages/API/JobListFiles.php(68): JobListFiles-&gt;getDetailedOutput()
#4 /usr/share/bacularis/protected/vendor/bacularis/bacularis-api/API/Modules/APIServerV2.php(49): JobListFiles-&gt;get()
#5 /usr/share/bacularis/protected/vendor/bacularis/bacularis-api/API/Modules/BaculumAPIServer.php(218): Bacularis\API\Modules\APIServerV2-&gt;get()
#6 /usr/share/bacularis/protected/vendor/bacularis/bacularis-api/API/Modules/BaculumAPIServer.php(201): Bacularis\API\Modules\BaculumAPIServer-&gt;runResource()
#7 ${PradoFramework}/Web/UI/TControl.php(1359): Bacularis\API\Modules\BaculumAPIServer-&gt;onInit()
#8 ${PradoFramework}/Web/UI/TCompositeControl.php(32): Prado\Web\UI\TControl-&gt;initRecursive()
#9 ${PradoFramework}/Web/UI/TTemplateControl.php(251): Prado\Web\UI\TCompositeControl-&gt;initRecursive()
#10 ${PradoFramework}/Web/UI/TPage.php(233): Prado\Web\UI\TTemplateControl-&gt;initRecursive()
#11 ${PradoFramework}/Web/UI/TPage.php(221): Prado\Web\UI\TPage-&gt;processNormalRequest()
#12 ${PradoFramework}/Web/Services/TPageService.php(547): Prado\Web\UI\TPage-&gt;run()
#13 ${PradoFramework}/Web/Services/TPageService.php(465): Prado\Web\Services\TPageService-&gt;runPage()
#14 ${PradoFramework}/TApplication.php(1262): Prado\Web\Services\TPageService-&gt;run()
#15 ${PradoFramework}/TApplication.php(386): Prado\TApplication-&gt;runService()
#16 ${DocumentRoot}/index.php(43): Prado\TApplication-&gt;run()
#17 {main}
</pre></code>
</div>
<div class="version">
2023-09-05 13:42 Apache/2.4.56 (Debian) <a href="https://github.com/pradosoft/prado">PRADO</a>/4.2.2
</div>
</body>
</html>
```

I've to look at the source code of some of the files mentioned in the stack trace, but I couldn't really find which database table column it is missing or what else might cause this issue.

I look forward to your help :-)

Thanks
Niels

**Comment by ganiuszka** [comment]
Hi Niels,

Thank you for your detailed report.

It looks that you use old Bacula Director ``9`` or older version. This error happens because in Bacula ``11.0.0`` there has been  changes the catalog format for storing file information. Before ``11.0.0`` the ``Filename`` value was stored in separate table. From ``11.0.0`` this column has been moved to the ``File`` table and the ``Filename`` table was dropped.

Bacularis works well with versions ``9``, ``11`` and ``13``. The one exception is that in Bacula Director <= ``9`` there is not working two Bacularis functions:

1. File list in job details (this one you reported)
2. Searching for file names in the second step of the restore wizard

Now after your message I am seeing that it might be good to add this information to the documentation. I will do that soon and let you know here.

I will keep this ticket opened until this time.

Thanks!

Best regards,
Marcin Haba (gani)

**Comment by nisori** [comment]
Hi Marcin,

thank you for getting back to me. You are right, this is Bacula version 9.6.7.  This server is a mission-critical system, and backup is a mission-critical service, so I've been reluctant to upgrade.

I'm happy for it to be treated as a documentation bug and when I will update Bacula, expect to be able to see the data :-)

Thanks again
Niels

**Comment by ganiuszka** [comment]
Hi Niels,

Thanks for your confirmation that you use Bacula ``9``.

I fully understand that Bacula upgrade can not be done every day, specially on the critical systems.

Yes, after upgrade Bacula to version ``11`` or higher, the data will be there :-)

Best regards,
Marcin Haba (gani)

**Comment by ganiuszka** [comment]
Hi Niels,

I am glad to let you know that I added information about this problem to the Bacularis documentation:

https://bacularis.app/doc/brief/troubleshooting.html#job-file-list-does-not-show-results

I am closing this ticket.

Thanks.

Best regards,
Marcin Haba (gani)
