### ISSUE TITLE
dark theme

### ISSUE THREAD

**Issue by empereira** [bacularis/bacularis-app#19]
hi,

Today's dark theme on the webgui is very hard on the eyes. Perhaps a dark gray palette would be less impactful.
![image](https://github.com/bacularis/bacularis-app/assets/29874574/d35e2dd2-6cef-4848-9639-1ca5f66e1c24)

#363232

**Comment by ganiuszka** [comment]
Hello Elias,

Thank you for your notice about the dark theme. I think you are right that the black colors could be less "aggressive".

Thanks for sharing your color value. I will check soon what we can do and let you know.

Best regards,
Marcin Haba (gani)

**Comment by ganiuszka** [comment]
Hello @empereira,

Thanks for waiting. I am writing to let know that the color palette in the dark theme has been mitigated. This change will be available from the next release. I am attaching a screenshot with the new colors.

Thanks again for indicating us this problem.

Best regards,
Marcin Haba (gani)

![Bacularis-Bacula-Web-Interface](https://github.com/bacularis/bacularis-app/assets/7281156/0c6bcd47-157a-45d5-9631-1e16fd7175b2)
