### ISSUE TITLE
Bacularis APP 2.0 - dark theme small error

### ISSUE THREAD

**Issue by johann8** [bacularis/bacularis-app#22]
Hello Marcin,
First of all, thank you for your work.
I use bacularis app version 2.2.0  as a [docker container](https://hub.docker.com/repository/docker/johann8/bacularis/general). When I activate the dark theme, I have a white background in one place like in the picture.
![Bacularis_APP_2 2 0_error](https://github.com/bacularis/bacularis-app/assets/13717874/d4d7f33a-3b49-4b84-822f-1667b35c39ef)

After login go to: Volumes => click on button "Quick edit"

Best regards
Johann

**Comment by ganiuszka** [comment]
Hello Johann,

Thank you very much for reporting this problem. Yes, you are right. I forgot about the dark theme when I was preparing this "Quick edit" drawer. I will fix it and the fix will be available in ``2.2.1`` soon. I will let know here once it will be ready.

BTW: Many thanks for your work on Bacularis Docker containers. It looks to be very nice project. If you agree I will add an info about your project at https://bacularis.app/news in a news form. Please let me know what do you think about it?

Best regards,
Marcin

**Comment by ganiuszka** [comment]
Hello @johann8

OK. I pushed a fix for that. Thanks!

Best regards,
Marcin Haba (gani)

**Comment by johann8** [comment]
Hello Marcin
Thank you very much for the very quick troubleshooting.

You can certainly link my project on the page. I may not be able to respond quickly enough to the possible problems because I have a full time job. I use bacula for data backup in the company.

Best regards
Johann

**Comment by ganiuszka** [comment]
Hello Johann

Thank you that you agreed on preparing this news. We prepared it and you can find it here:

https://bacularis.app/news/64/36/Bacularis-and-Bacula-Docker-Hub-project/d,Bacularis%20news%20details

No problem with slow responding. It is good to hear that you use Bacula in your company :-)

Thanks again for your project on Docker Hub.

I am closing this ticket. In case questions or problems, please let us know.

Best regards,
Marcin Haba (gani)
