### ISSUE TITLE
Lost admin password

### ISSUE THREAD

**Issue by sitemapxml** [bacularis/bacularis-app#27]
Hello,

I have lost the password to access bacularis app (not HTTP auth, I think on this [login screen](https://i.imgur.com/I95Eo1B.png)).
Although this seems as a basic question, I didn't manage to find an answer in the docs. 
How can I reset the admin password?

**Comment by ganiuszka** [comment]
Hello @sitemapxml,

Thanks for your support question.

Yes, of course, you can reset your admin password. To do it, you need a tool to set password in APR-MD5 format, like ``htpasswd`` tool. On CentOS/RHEL it is in package ``httpd-tools``, on Debian/Ubuntu it is package ``apache2-utils``. I assume that you installed Bacularis using binary packages and you use local authentication method. So after you can run this command from the root user account:

```
htpasswd /etc/bacularis/Web/bacularis.users YOURADMINUSER
```

In place YOURADMINUSER you need to type your admin username.

You will be two times asked about typing a new password for your user;

```
New password: 
Re-type new password: 
Updating password for user YOURADMINUSER
```

And that is all.

Please let us know if it helped. Good luck!

Best regards,
Marcin Haba (gani)

**Comment by ganiuszka** [comment]
BTW: You are right. It might be a good topic for the section in the ``Troubleshooting`` chapter of the Bacularis documentation. I will try to prepare something there. Thanks!

**Comment by ganiuszka** [comment]
Hello @sitemapxml,

I have prepared this new section in the Bacularis documentation. You can find it here:

https://bacularis.app/doc/brief/troubleshooting.html#i-forgot-my-admin-password-what-should-i-do

Thank you!

Best regards,
Marcin Haba (gani)

**Comment by sitemapxml** [comment]
Hello Marcin,

Thank you for the detailed answer.
I used the method you have described to change the password, and it worked perfectly.

> I assume that you installed Bacularis using binary packages and you use local authentication method.

Yes, I use local authentication method, but forgot to mention that (sorry for this - will try to be more specific in the future :sweat_smile:).

Since you have taken actions quickly, I will close this issue.
Thank you for your help and for keeping docs up to date and complete.

Regards
