### ISSUE TITLE
Bacularis APP - dark theme small CSS error

### ISSUE THREAD

**Issue by johann8** [bacularis/bacularis-app#32]
Hello Marcin,

First of all, thank you for your work.
I use bacularis app version 2.5.1 as a [docker container](https://hub.docker.com/repository/docker/johann8/bacularis/general). I have discovered a CSS error in one place like in the picture:
![Job_Estimate_error](https://github.com/bacularis/bacularis-app/assets/13717874/db2d9a88-3943-4650-aa15-8e5abb90be45)

After login go to: Jobs => Choose any job - Column Action - Button Details click => Button Run job => Button Estimate job => Row output

Best regards
Johann

**Comment by ganiuszka** [comment]
Hello @johann8

Thanks for your kind words :smile: The same I would like to say to you, that I thank you for your Bacularis container project in the Docker Hub.

For the main problem, many thanks for catching and reporting it. Yes, it is a bug in CSS.

I fixed it, so it will be available from the next minor Bacularis release.

Best regards,
Marcin Haba (gani)
