### ISSUE TITLE
missing style / empty pages / invalid director

### ISSUE THREAD

**Issue by rnagy** [bacularis/bacularis-app#35]
Hi

After installing bacularis 2.6.0 the first visit to the website properly brings up authentication and after logging in,
the install wizard shows up but without any styling on the page.

![Screenshot 2024-03-12 at 11-20-07 Bacularis - Bacula Web Interface](https://github.com/bacularis/bacularis-app/assets/166914/5f46a8b6-6731-4120-8ada-af33d009ee33)

After some testing adding a simple echo("@"); to the begining of index.php makes it load the actual styles and the installation
can be finished with all tests returning OK, however after logging in all the pages are empty or returning an invalid director
error.

![Screenshot 2024-03-12 at 11-21-55 Bacularis - Bacula Web Interface](https://github.com/bacularis/bacularis-app/assets/166914/fdf51cfa-f994-485b-a593-74751f99b6f1)

Going to the API panel, none of the endpoints return anything, even though all the replies are 200 according to the log.

XXX.XXX.XXX.XXX - admin [12/Mar/2024:11:25:39 +0100] "GET /api/v2/jobs?limit=10 HTTP/1.1" 200 8154 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"

At this point removing the echo from index.php, the API replies can be seen, but there are no styling on the page
at all. So at this point I think the empty pages are caused by the additional echo, so the missing styling is the actual issue.

![Screenshot 2024-03-12 at 11-28-34 Bacularis - Bacula Web Interface](https://github.com/bacularis/bacularis-app/assets/166914/2f0a5267-1641-4616-a385-65d06627832a)

`
XXX.XXX.XXX.XXX - admin [12/Mar/2024:11:30:20 +0100] "GET /panel/ HTTP/1.1" 200 15828 "http://REDACTED:9097/web/director//" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
XXX.XXX.XXX.XXX - - [12/Mar/2024:11:30:20 +0100] "GET /assets/f2770455/baculum.css?ver=2.6.0 HTTP/1.1" 200 20095 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
XXX.XXX.XXX.XXX - - [12/Mar/2024:11:30:20 +0100] "GET /assets/4502e5b/prado.js HTTP/1.1" 200 32175 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
XXX.XXX.XXX.XXX - - [12/Mar/2024:11:30:20 +0100] "GET /assets/4502e5b/activecontrols/ajax3.js HTTP/1.1" 200 28032 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
XXX.XXX.XXX.XXX - - [12/Mar/2024:11:30:20 +0100] "GET /assets/4502e5b/controls/controls.js HTTP/1.1" 200 13974 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
XXX.XXX.XXX.XXX - - [12/Mar/2024:11:30:20 +0100] "GET /assets/4cd33fa/themes/base/jquery-ui.css HTTP/1.1" 200 35973 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
XXX.XXX.XXX.XXX - - [12/Mar/2024:11:30:20 +0100] "GET /assets/4502e5b/activecontrols/activecontrols3.js HTTP/1.1" 200 10383 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
XXX.XXX.XXX.XXX - - [12/Mar/2024:11:30:20 +0100] "GET /assets/d6a2e0af/dataTables.responsive.min.js?ver=2.6.0 HTTP/1.1" 200 14597 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
XXX.XXX.XXX.XXX - - [12/Mar/2024:11:30:20 +0100] "GET /assets/bb4d50d7/dataTables.buttons.min.js?ver=2.6.0 HTTP/1.1" 200 25485 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
XXX.XXX.XXX.XXX - - [12/Mar/2024:11:30:20 +0100] "GET /assets/bb4d50d7/buttons.html5.min.js?ver=2.6.0 HTTP/1.1" 200 25138 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
XXX.XXX.XXX.XXX - - [12/Mar/2024:11:30:20 +0100] "GET /assets/bb4d50d7/buttons.colVis.min.js?ver=2.6.0 HTTP/1.1" 200 3267 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
XXX.XXX.XXX.XXX - - [12/Mar/2024:11:30:20 +0100] "GET /assets/4227f0a9/dataTables.select.min.js?ver=2.6.0 HTTP/1.1" 200 14277 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
XXX.XXX.XXX.XXX - - [12/Mar/2024:11:30:20 +0100] "GET /assets/552c6492/misc.js?ver=2.6.0 HTTP/1.1" 200 11401 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
XXX.XXX.XXX.XXX - - [12/Mar/2024:11:30:20 +0100] "GET /assets/8a3c9400/jquery.dataTables.min.js?ver=2.6.0 HTTP/1.1" 200 87110 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
XXX.XXX.XXX.XXX - - [12/Mar/2024:11:30:20 +0100] "GET /assets/aa252275/w3.css?ver=2.6.0 HTTP/1.1" 200 23427 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
XXX.XXX.XXX.XXX - - [12/Mar/2024:11:30:20 +0100] "GET /assets/1ca2589a/jquery.dataTables.min.css?ver=2.6.0 HTTP/1.1" 200 13624 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
XXX.XXX.XXX.XXX - - [12/Mar/2024:11:30:20 +0100] "GET /assets/d74d2b0e/responsive.dataTables.min.css?ver=2.6.0 HTTP/1.1" 200 4238 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
XXX.XXX.XXX.XXX - - [12/Mar/2024:11:30:20 +0100] "GET /assets/567dafab/buttons.dataTables.min.css?ver=2.6.0 HTTP/1.1" 200 13204 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
XXX.XXX.XXX.XXX - - [12/Mar/2024:11:30:20 +0100] "GET /themes/Baculum-v2/fonts/css/fontawesome-all.min.css?ver=2.6.0 HTTP/1.1" 200 102641 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
XXX.XXX.XXX.XXX - - [12/Mar/2024:11:30:20 +0100] "GET /assets/26681442/avatar2.png HTTP/1.1" 200 8490 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
XXX.XXX.XXX.XXX - - [12/Mar/2024:11:30:20 +0100] "GET /assets/26681442/logo.png HTTP/1.1" 200 3038 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
XXX.XXX.XXX.XXX - - [12/Mar/2024:11:30:20 +0100] "GET /assets/cf3d3576/jquery.js HTTP/1.1" 200 292458 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
XXX.XXX.XXX.XXX - - [12/Mar/2024:11:30:21 +0100] "GET /assets/4cd33fa/jquery-ui.js HTTP/1.1" 200 520714 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
XXX.XXX.XXX.XXX - - [12/Mar/2024:11:30:21 +0100] "GET /assets/26681442/favicon.ico HTTP/1.1" 200 4286 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
XXX.XXX.XXX.XXX - admin [12/Mar/2024:11:30:21 +0100] "POST /panel/ HTTP/1.1" 200 1862 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"

`
The system is running nginx with the default included configuration of bacularis with php 8.2.

**Comment by ganiuszka** [comment]
Hello @rnagy

Thank you for reporting this problem and for all details.

It is interesting case. It looks that you use the web server authentication, right? In the provided access log we can see that requests for getting CSS and JavaScript files are not protected by web server authentication but PHP files are protected:

**CSS**:
```
XXX.XXX.XXX.XXX - - [12/Mar/2024:11:30:20 +0100] "GET /assets/f2770455/baculum.css?ver=2.6.0 HTTP/1.1" 200 20095
```

**JS**:
```
XXX.XXX.XXX.XXX - - [12/Mar/2024:11:30:20 +0100] "GET /assets/4502e5b/prado.js HTTP/1.1" 200 32175 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
```

**PHP**:
```
XXX.XXX.XXX.XXX - admin [12/Mar/2024:11:30:21 +0100] "POST /panel/ HTTP/1.1" 200 1862 "http://REDACTED:9097/panel/" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0"
```

The ``admin`` user probably comes from the web server authentication. It can make a problem because Bacularis uses native basic authentication, not authentication from the web server. Could you tell us if you have any custom basic authentication in the web server? If yes, could you disable it for test?

I have also question about how you installed the Bacularis? I mean, did you use: binary packages or manual installation or PHP composer... ?

Thank you in advance for providing the additional information.

Best regards,
Marcin Haba (gani)

**Comment by rnagy** [comment]
Hi

I am using a bone stock nginx configuration on this because it is a test instance and I only have one
server block and that is coming from `protected/samples/webserver/bacularis-nginx.conf`. There is nothing else configured, no authentication

Bacularis was installed by following the README.md file in the bacularis-app repo using composer.

**Comment by ganiuszka** [comment]
Hello @rnagy

Thank you for quick response and answer.

This type of behavior can happen when in Nginx the mime types file is not loaded. You can find it in the main Nginx configuration file ``nginx.conf``. There should be line similar to this one:

```
include             /etc/nginx/mime.types;
```

Could you confirm that you have the ``mime.types`` file included there?

If you have it included, could  you look inside this ``mime.types`` file in there is line like this:

```
    text/css                                         css;
```

Thanks in advance for this checking.

Best regards,
Marcin Haba (gani)

**Comment by rnagy** [comment]
> Hello @rnagy
> 
> Thank you for quick response and answer.
> 
> This type of behavior can happen when in Nginx the mime types file is not loaded. You can find it in the main Nginx configuration file `nginx.conf`. There should be line similar to this one:
> 
> ```
> include             /etc/nginx/mime.types;
> ```
> 
> Could you confirm that you have the `mime.types` file included there?
> 
> If you have it included, could you look inside this `mime.types` file in there is line like this:
> 
> ```
>     text/css                                         css;
> ```
> 
> Thanks in advance for this checking.
> 
> Best regards, Marcin Haba (gani)

Hey,

Oh my god... I feel completely stupid now. Yes indeed I had the mime.types include accidentally removed.....

Thank you! :)

**Comment by ganiuszka** [comment]
Hello @rnagy,

Great. Many thanks for the confirmation.

Happy using Bacularis :-)

Best regards,
Marcin Haba (gani)
