### ISSUE TITLE
Bacularis Dashboard Fails to Load Because of Scripting Error in graphs.js

### ISSUE THREAD

**Issue by joeysr20det** [bacularis/bacularis-app#4]
Hello,

We've been using Bacularis for a few months now and really like it! In the last couple of days, I noticed my dashboard is failing to load completely. Reviewing the debug console, it appears to be an issue in graph.js. The iso_date_to_timestamp function is receiving a null and thus the function fails on its first line at iso_date.split:

`var iso_date_to_timestamp = function(iso_date) {
	var date_split = iso_date.split(' ');
	var date = date_split[0].split('-');
	if (date_split[1]) {
		var time = date_split[1].split(':');
		var date_obj = new Date(date[0], (date[1] - 1), date[2], time[0], time[1], time[2]);
	} else {
		var date_obj = new Date(date[0], (date[1] - 1), date[2], 0, 0, 0);
	}
	return date_obj.getTime();
}`

After looking over the script it appears that the change function called on the 'date from' must be receiving a null target.value. I assume it maybe has something to do with the change of the year to 2023 as it worked just a few days ago.

For reference, we are running Bacula 9.6.7 on Ubuntu 22.04 LTS with the current latest version of Bacularis 1.3.0 available in your Ubuntu 22 (Jammy) repo. My user agent is Chrome version 108.0.5359.125 (Official Build) (64-bit).

You all have done a great job on Bacularis! We're really happy with it and have used just about all of its abilities with zero issues prior to this!

**Comment by joeysr20det** [comment]
![Untitled](https://user-images.githubusercontent.com/19842458/210611820-b4b4f0e4-8c8d-46ab-86ca-4ca740321876.png)

**Comment by ganiuszka** [comment]
Hello joeysr20det,

Thank you for your kind words about Bacularis. It is great to hear so nice feedback :-)

Also thank you for the detailed bug report.

There are cases when older Bacula Director version marks jobs as cancelled with not properly set start time for jobs. I guess it can be this case. Did you cancelled not started (queued) jobs lately? If yes, then fix for this problem you can see here:

https://gitlab.bacula.org/bacula-community-edition/bacula-community/-/commit/2d736705e72ea9259f49e10ec6a17f2bfd751318

It has been fixed in Bacula beta 11.3.2 and in first stable Bacula 13.0.0.

Could I ask you about confirming that it is this case? You can check it by listing jobs in bconsole:

```
list jobs
```

and see starttime column for finished jobs. Is there any with empty start time?

If it is this case, as a workaround I would propose to delete these failed jobs by bconsole ``delete jobid=xxxx`` command.

Best regards,
Marcin Haba (gani)

**Comment by joeysr20det** [comment]
Gani,

Thanks for the speedy reply!

Yes, I'm hoping we can upgrade to a newer version of Bacula soon :) The Ubuntu 22.04 LTS doesn't currently have the bacula package available, but another user had corrected, compiled, and hosted 9.7.6 in his own PPA so we've been running on that. This is a pretty fresh setup. We've just moved out of our testing phase with Bacula over the last several months and are getting ready to go to production. We've started with fresh storage drives and a fresh MySql database, thus the small number of jobs...

I wasn't aware of that bug. I just checked again and the dashboard is working again. I did have one job running and a few queued jobs at the time I noticed the issue. When I run list jobs in bconsole now, I get the following:

`
+-------+--------------------------+---------------------+------+-------+----------+-----------------+-----------+
| JobId | Name                               | StartTime                   | Type | Level | JobFiles | JobBytes        | JobStatus |
+-------+--------------------------+---------------------+------+-------+----------+-----------------+-----------+
|     1 | Job_Backup_Catalog_Disk2 | 2023-01-02 13:19:03 | B      | F     |        1     |          29,465         | T         |
|     2 | Job_Backup_txr2_Disk2       | 2023-01-02 13:19:47 | B      | F     |  917,994  | 693,364,797,970 | T         |
|     3 | Job_Backup_txr3_Disk2       | 2023-01-02 17:06:10 | B      | F     |  997,742  | 103,735,646,431 | T         |
|     4 | Job_Backup_Catalog_Disk2 | 2023-01-04 11:38:59 | B      | F     |        1      |     334,740,841    | T         |
|     5 | Job_Backup_txr2_Disk2       | 2023-01-04 11:39:21 | B      | I     |    5,743    |   1,930,805,589    | T         |
|     6 | Job_Backup_txr3_Disk2       | 2023-01-04 12:57:51 | B      | I     |   10,123   |   1,761,917,345    | T         |
+-------+--------------------------+---------------------+------+-------+----------+-----------------+-----------+
`

So just for grins I kicked off all of the same jobs again and sure enough, I had a couple NULL values in the start time column for the jobs that were queued but not yet started. You hit that one on the head :)

I'll let my backup admin know and hopefully Bacula 11 will be available in the repo soon. I apologize for the false bug report on this. 

Thanks again for the speedy reply!
Joey

**Comment by ganiuszka** [comment]
Hello joeysr20det,

Thanks for the confirmation and details.

I prepared a fix on the Bacularis side that it should work with older Bacula versions too.

It will be available in next Bacularis version ``1.3.1`` soon.

If you want you can try this fix or you can wait on ``1.3.1``.

Thanks for your help in this ticket. I am closing it.

Best regards,
Marcin Haba (gani)
