### ISSUE TITLE
Ability to add filter for LDAP auth

### ISSUE THREAD

**Issue by dquinton-teicee** [bacularis/bacularis-app#40]
Hello,
First of all, thank you for this
It would be great to be able to set an LDAP filter for user authentication, for example :
```
(&(objectClass=inetOrgPerson)(memberOf=cn=bacularis,cn=groups,cn=accounts,dc=domain,dc=en)(!(nsaccountlock=TRUE)))
```

Ideally, we could have several filters to assign different roles depending on the ldap group, for example

Thanks a lot!

**Comment by ganiuszka** [comment]
Hello @dquinton-teicee

Thank you very much for your feature request.

Yes, you are right. I looks to be a really useful function to add support for LDAP filters.

We will add it to Bacularis. It will be available in the next release.

Thanks!

Best regards,
Marcin Haba (gani)

**Comment by ganiuszka** [comment]
Hello @dquinton-teicee

I am please to let you know that the LDAP filters support has been added to Bacularis.

These filters are RFC 4515 compatible.

Thank you again for this feature request.

Best regards,
Marcin Haba (gani)

**Comment by dquinton-teicee** [comment]
Thank you for your reactivity ! Have a good day
