### ISSUE TITLE
Add SyncOnClose directive support to Device resource configuration

### ISSUE THREAD

**Issue by ganiuszka** [bacularis/bacularis-app#45]
Hello Everybody,

Please add the ``SyncOnClose`` directive support to the ``Device`` resource configuration.

This problem has been reported by Jose Alberto on the Bacula-Users mailing list:

https://sourceforge.net/p/bacula/mailman/message/58774171/

Best regards,
Marcin Haba (gani)

**Comment by sitemapxml** [comment]
Hi, It this also relatable to disk-based backups, or just to tape drives?

**Comment by ganiuszka** [comment]
Hi @sitemapxml

I think that yes. It can be used for every device that works with fsync() call.

https://man7.org/linux/man-pages/man2/fsync.2.html

This directive adds an additional capability to storage device that causes flushing data when the device is closing.

https://www.bacula.org/15.0.x-manuals/en/main/Storage_Daemon_Configuratio.html#18935

Best regards,
Marcin Haba (gani)

**Comment by ganiuszka** [comment]
Hello Everybody,

I am glad to let you know that ``SyncOnClose`` directive support has been added to Bacularis.

Best regards,
Marcin Haba (gani)
