### ISSUE TITLE
Volume list & volume detail: incorrect display of date in "last written" column

### ISSUE THREAD

**Issue by nisori** [bacularis/bacularis-app#5]
I have a volume that is in status Full, but has never been written to; it is on an external hard drive that ran out of space because of other volumes on the same drive.
In bconsole, the Last Written value shown is "0000-00-00 00:00:00", which in bacularis is shown as "-68118-04-26 23:58:45" (yes, a negative value!). Accordingly, the When Expire is shown in bacularis as "-66122-04-02 23:58:45".

![bacularis-bug](https://user-images.githubusercontent.com/90049468/218085059-d467fc09-3bf4-4d94-b76e-063afb1714b7.png)

**Comment by ganiuszka** [comment]
Hello nisori,

Thank you for your detailed bug report.

Yes, it is interesting case. Fortunately now it is fixed.

The fix is available from next Bacularis release.

Best regards,
Marcin Haba (gani)
