### ISSUE TITLE
Reopen: Volume list & volume detail: incorrect display of date in "last written" column

### ISSUE THREAD

**Issue by nisori** [bacularis/bacularis-app#6]
Hello Marcin,

I'm afraid I have to reopen issue #5.

The version 1.4.0 was installed today, but the problem partially remains:
1. the Volumes list (table view) is still incorrect - see bottom part of the image
2. The volume detail view now shows the "Last Written" correctly as "0000-00-00 00:00:00"
3. The "When expire" in the volume detail view still doesn't make sense (it shows "0001-11-29 00:00:00").

![bacularis-bug-2](https://user-images.githubusercontent.com/90049468/220715090-988cc699-0d10-46a8-8b49-e63dc06d54d2.png)

Could you please take another look at this issue?

Many thanks
Niels (nisori)

**Comment by ganiuszka** [comment]
Hello Niels,

Thank you for reopening issue #5 and for your report.

OK, I hope that now we have nailed it down. The fix will be available in ``1.4.1``. We should be able to release it in about a week.

I am closing this ticket. Thanks.

Best regards,
Marcin Haba (gani)
