### ISSUE TITLE
Using copy config together with selecting jobdefs causes collapsing new job window

### ISSUE THREAD

**Issue by ganiuszka** [bacularis/bacularis-app#62]
Hello Everybody,

This bug has been reported by Jack Vande Bunte on the Bacula-Users mailing list:

https://sourceforge.net/p/bacula/mailman/message/58829341/

It is about collapsing the new job window when first is used copying the configuration and after is selected a jobdefs in the job form. Jack described this behavior in details on the Bacula-Users mailing list.

Here is a patch:

[bugfix_copy_config_with_jobdefs.patch.txt](https://github.com/user-attachments/files/17429073/bugfix_copy_config_with_jobdefs.patch.txt)

Jack, could I ask you about trying the attached patch and checking if it solves the described problem? It can be done as below:

```
cp bugfix_copy_config_with_jobdefs.patch.txt /usr/share/bacularis/protected/Web/Portlets
cd /usr/share/bacularis/protected/Web/Portlets
patch -p3 < bugfix_copy_config_with_jobdefs.patch.txt
```

This patch can be easily applied on every Bacularis versions ``3`` and ``4``.

Thanks in advance for trying it and letting us know.

Best regards,
Marcin Haba (gani)

**Comment by jvbunte** [comment]
I can confirm that this patch does indeed fix the issue. I am even more happy that I was not insane and it was an actual bug. 

Thank you so much for looking into this and resolving it so quickly!

**Comment by jvbunte** [comment]
FWIW: the Bacularis docker containers, both bacularis-web and bacularis-standalone also suffer from this issue.

**Comment by jvbunte** [comment]
Also for posterity, anyone following the link to my mailing list post above, I had misspoken on my original email to the list, the problem child function was "JobDefs" and not "FileSet". I think I mixed them up because I was trying to fully document the troubleshooting steps I had done and just blew that one I guess.

**Comment by ganiuszka** [comment]
Hello Jack (@jvbunte),

Thank you very much for your quick help with trying this patch and for confirming that it works. Now I added this patch to the ``bacularis-web`` repository.

Also thanks for mentioning the Docker images. We update the images in Docker.com repositories on every release. This fix will be available in the next Bacularis release. As always, after releasing it, we will update the images.

I think we can successfully close this issue. Thanks again.

Best regards,
Marcin Haba (gani)
