### ISSUE TITLE
Add support for LDAP with STARTTLS

### ISSUE THREAD

**Issue by MartLTB** [bacularis/bacularis-app#8]
We would like to use our LDAP service with Bacularis but it only supports connections using STARTTLS while Bacularis only offers LDAPS. From what I know STARTTLS is the current standard and the current php-ldap should also support it so it would be great to see Bacularis support for LDAP with STARTTLS added.

**Comment by ganiuszka** [comment]
Hello MartLTB,

Thank you for this feature request.

Yes, you are right about StartTLS. We will try to add this option quickly.

Thanks.

Best regards,
Marcin Haba (gani)

**Comment by ganiuszka** [comment]
Hi MartLTB,

I am glad to let you know that we added the StartTLS option to LDAP connection.

It will be available from next ``1.7.0`` release.

Thanks.

Best regards,
Marcin Haba (gani)
